package server.network;

public enum ServerPreGameProtocol {
    REGISTER_SUCCESS,
    REGISTER_FAIL,
    LOGIN_SUCCESS,
    LOGIN_FAIL,
    TOP_LIST_SENT,
    NO_REGISTERED_PLAYERS,
    REGISTER_FAIL_USERNAME_TAKEN, INVITE_ACCEPTED, PLAYER_NOT_FOUND, FRIEND_INVITE, INVITE_REJECTED, PLAYER_NOT_AVAILABLE, GAME_START, LOGIN_RESPONSE, INVITE,
    
}
