package server.network;

public enum ServerPreGameProtocol {
    REGISTER_SUCCESS,
    REGISTER_FAIL,
    LOGIN_SUCCESS,
    LOGIN_FAIL,
    TOP_LIST_SENT,
    NO_REGISTERED_PLAYERS,
    REGISTER_FAIL_USERNAME_TAKEN, PLAYER_NOT_FOUND, FRIEND_INVITE, PLAYER_NOT_AVAILABLE, INVITE_ACCEPTED, INVITE_REJECTED, GAME_START, INVITE, INVITE_RESPONSE,
    
}
