package client.network;

public enum ClientPreGameProtocol {
    REGISTER_USER,
    LOGIN_USER,
    SEARCH_FOR_PLAYER,
    START_RANDOM_GAME,
    CLIENT_INVITE_ACCEPTED, REJECT_INVITE, SHOW_TOP_LIST, EXIT_CLIENT
}